# A string used to distinguish different Supabase projects on the same host.
project_id = "supastripe"

[api]
enabled = false

[db]
major_version = 15

[studio]
enabled = false

[auth]
enabled = false

[realtime]
enabled = false

[storage]
enabled = false

[edge_runtime]
enabled = false

[analytics]
enabled = false