name: Process Due Payments

on:
  schedule:
    - cron: '0 0 * * *'  # Run daily at midnight UTC

jobs:
  process-payments:
    runs-on: ubuntu-latest
    steps:
    - name: Trigger Supabase Function
      run: |
        curl -X POST https://imcufcrfdoacrvbifcor.supabase.co/functions/v1/process-due-payments \
        -H "Authorization: Bearer ${{ secrets.SUPABASE_SERVICE_ROLE_KEY }}" \
        -H "Content-Type: application/json"
